Fix godep-restore
sttts/origin pull request #66
Opened 2017-04-06 09:52 UTC by sttts

2017-04-07 05:53 UTC, sttts commented
/cc @stevekuznetsov, ptal at the `hack/godep-*.sh` changes

2017-04-07 11:08 UTC, mfojtik commented
@ncdc i think we should start kicking `godep` tool out from origin repo and switch to `golang/dep`... every release we adding more hacks/band-aid to survive. Maybe we can join forces on this (PM + your team) .

2017-04-07 11:09 UTC, ncdc commented
Only if dep actually works. But I agree. The godep author has stated it is
basically eol.
On Fri, Apr 7, 2017 at 7:08 AM Michal Fojtik <notifications@github.com>
wrote:

> @ncdc <https://github.com/ncdc> i think we should start kicking godep
> tool out from origin repo and switch to golang/dep... every release we
> adding more hacks/band-aid to survive. Maybe we can join forces on this (PM
> + your team) .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sttts/origin/pull/66#issuecomment-292509559>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAABYjTWIda4PsMB6vaszS_xAle1SCgGks5rthkWgaJpZM4M1XgG>
> .
>

2017-04-07 11:47 UTC, stevekuznetsov requested changes

2017-04-07 11:47 UTC, stevekuznetsov commented on hack/godep-save.sh
> +which jq >/dev/null || { echo "Please install jq." 1>&2; exit 1; }
```
os::util::ensure::system_binary_exists "jq"
```

2017-04-07 11:47 UTC, stevekuznetsov commented on hack/godep-save.sh
> +      test -n "$(ls $FAKEPKG/*.go 2>/dev/null)" && { echo "'fork::with::fake::packages $PKG $FAKEPKG' failed because $FAKEPKG already exists." 1>&2; exit 1; }
Prefer to use `if` instead of `test && ||`

2017-04-07 11:47 UTC, stevekuznetsov commented on hack/lib/cleanup.sh
> +    for directory in $( find "${BASETMPDIR}" -depth 2 ); do
You're going to get a conflict on this I think, someone is currently fixing it.

2017-04-10 07:03 UTC, sttts commented on hack/lib/cleanup.sh
> +    for directory in $( find "${BASETMPDIR}" -depth 2 ); do
Will drop this change. There is still some error messages, might be Mac related.

2017-04-10 07:15 UTC, merged

2017-04-10 12:49 UTC, stevekuznetsov commented on hack/lib/cleanup.sh
> +    for directory in $( find "${BASETMPDIR}" -depth 2 ); do
https://github.com/openshift/origin/pull/13691